name: docker

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV     

      - name: pwd
        run: |
          pwd

      - name: docker build
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/docker:v${{ env.RELEASE_VERSION }} ./Dockerfile

      - name: docker images check
        run: docker images
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: docer push
        run: | 
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/docker:v${{ env.RELEASE_VERSION }}
    
      - name: EC2 Docker Run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker rm -f $(docker ps -qa)
            docker run -d -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/docker:v${{ env.RELEASE_VERSION }}
